### ISSUE TITLE
response_type=id_token+token

### ISSUE THREAD

**Issue by afreakk** [ory/hydra-maester#101]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra-maester/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra-maester/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

If i do implicit grant with `response_type=id_token+token` and i configure `OAuth2Client` with:
```
  responseTypes:
    - id_token
    - token
```
I get `The client is not allowed to request response_type 'id_token token'.`
_BUT_ If i manually  create the client using `POST` & json body with
```
    "response_types": [
      "id_token token"
    ],
```
I _am_ allowed to do implicit grant with `response_type=id_token+token`.
But maester wont let me configure response_types like that:
```
  responseTypes:
    - "id_token token"
```
Results in:
```
invalid: spec.responseTypes: Unsupported value: "id_token token": supported values: "id_token", "code", "token"
```

### Reproducing the bug

1. Create `kind: OAuth2Client` with:
   ```
     responseTypes:
    - "id_token token"


### Relevant log output

_No response_

### Relevant configuration

_No response_

### Version

oryd/hydra-maester:v0.0.24

### On which operating system are you observing this issue?

_No response_

### In which environment are you deploying?

Kubernetes with Helm

### Additional Context

_No response_

**Comment by Demonsthere** [comment]
Hello there,
The error is generated from this [kubebuilder annotation](https://github.com/ory/hydra-maester/blob/master/api/v1alpha1/oauth2client_types.go#L132)

```
// +kubebuilder:validation:Enum=id_token;code;token
```

It seems it would be enough to expand the enum here and regen the CRD

**Comment by Demonsthere** [comment]
Hello there,
For clarification, are you trying to pass an array, or a single field with the value of "id_token token"? The following sample is working just fine

```yaml
apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: my-oauth2-client
  namespace: default
spec:
  grantTypes:
    - client_credentials
    - implicit
    - authorization_code
    - refresh_token
  responseTypes:
    - id_token
    - code
    - token
  scope: "read write"
  secretName: my-secret-123
```
