### ISSUE TITLE
Ability to set template/metadata on generated secrets

### ISSUE THREAD

**Issue by adamstrawson** [ory/hydra-maester#118]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra-maester/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra-maester/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

We have tooling that performs actions when a configmap/secret changes based on annotations. 

It would be nice to be able to include metadata (specially annotations) within the secret that `hydra-maester` creates.

### Describe your ideal solution

Within the Custom Resource, i'd like to define a spec template form which to create the secret, in a similar format to below:

```yaml
apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: my-client
spec:
  grantTypes:
    - client_credentials
  scope: my-scope
  secret:
    name: my-test-secret
    template:
      metadata:
        annotations:
          hello/world: foo
  clientName: foobar
```

The generated secret would then look like:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-test-secret
  namespace: test
  annotations:
    hello/world: foo
  ownerReferences:
    - apiVersion: hydra.ory.sh/v1alpha1
      kind: OAuth2Client
      name: my-client
      uid: 1234-1234
data:
  client_id: aGVsbG8tZGlkLXlvdS1yZWFsbHktY2hlY2stdGhpcw==
  client_secret: aS13b3VsZC1saWtlLXNvbWUtcGllLXBsZWFzZQ==
type: Opaque
```

For backwards compatibility, we could support both `secretName` and `secret.name` with the intention of deprecating `secretName` in a future version.

### Workarounds or alternatives

N/A

### Version

N/A

### Additional Context

Happy to PR if we feel this is a welcome addition.
