### ISSUE TITLE
Allow to set multiple client ids/secrets in a same K8s secret

### ISSUE THREAD

**Issue by burahimu** [ory/hydra-maester#157]
### Preflight checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra-maester/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra-maester/blob/master/CONTRIBUTING.md).
- [x] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe your problem

In a specific context, I want to be able to define client_id_key and client_secret_key per client definition. Currently, it's only possible to define a env var to override the key for all clients.

### Describe your ideal solution

Add clientIdKey and clientSecretKey in `Oauth2Client` spec

```yaml
---
apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: my-client-1
spec:
  secretName: my-secret
  clientIdKey: client-id-2
  clientSecretKey: client-secret-2
...
---
apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: my-client-2
spec:
  secretName: my-secret
  clientIdKey: client-id-2
  clientSecretKey: client-secret-2
...
```

### Workarounds or alternatives

I made a loop in my chart to load secrets

```gotmpl
{{- range $clientName, $clientConfig := .Values.oauth2client.clients }}
- name: {{ $clientConfig.clientIdEnvVarName  }}
  valueFrom:
    secretKeyRef:
      name: {{ $clientName }}-oauth2client-secret
      key: CLIENT_ID
- name: {{ $clientConfig.clientSecretEnvVarName }}
  valueFrom:
    secretKeyRef:
      name: {{ $clientName }}-oauth2client-secret
      key: CLIENT_SECRET
{{- end }}
```

WDYT to do the following:

```yaml
envFrom:
    - secretRef:
        name: my-secret
```

### Version

0.0.36
