### ISSUE TITLE
Created secret name should match `secretName` in spec

### ISSUE THREAD

**Issue by paulbdavis** [ory/hydra-maester#29]
Creating a client with this manifest works correctly

```yaml
apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: my-app-oauth-client
spec:
  grantTypes:
    - client_credentials
    - implicit
    - authorization_code
    - refresh_token
  responseTypes:
    - id_token
    - code
    - token
  scope: "read write"
  secretName: my-app-oauth-client
```

But using the following causes the secret name to not match the one in the spec (the `metadata.name` of the client was changed)

```yaml
apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: my-app
spec:
  grantTypes:
    - client_credentials
    - implicit
    - authorization_code
    - refresh_token
  responseTypes:
    - id_token
    - code
    - token
  scope: "read write"
  secretName: my-app-oauth-client
```

With the above, the created secret is `my-app` instead of `my-app-oauth-client`
