### ISSUE TITLE
Set clientId for OAuth2Client

### ISSUE THREAD

**Issue by PeteMac88** [ory/hydra-maester#66]
Hey there,
is there a way of setting a fixed `clientId` for the OAuth2Client CRD. If not do you think it makes sense to add this because its quite dangerous that if a resource is accidentally removed that the new client gets a new Id.

**Comment by piotrmsc** [comment]
Hey @PeteMac88 , thx for trying it out!

Yes, you can set the client pair (clientID and clientSecret) by yourself.
To do so, you will need to first create k8s secret and the reference it in the Oauth2Client CR. Take a look on the example : 

```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  client_id: $BASE64_ID
  client_secret: $BASE64_SECRET
---
apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: example
spec:
  grantTypes:
    - "client_credentials"
  scope: "read write"
  secretName: mysecret
```
